trigger: none
  # batch: "true"
  # branches:
  #   include: [users/benwilk/shared]
  # tags:
  #   exclude: [NoBuild]

parameters:
  - name: STAGE
    displayName: Deployment Stage
    type: string
    default: FD.CDN
    values:
      - 00-ALL-SUB
      - 01-ALL-RG
      - FD.CDN
      - FD.CDNPolicy
      - SA

  - name: CN
    displayName: AFD Endpoint
    type: string
    default: '.'
    values:
      - '.'
      - cdn01
      - apim01
      - shared01apim01

  - name: CN2
    displayName: Endpoint
    type: string
    default: 'acu1brwpstd2sadata1'
    values:
      - '.'
      - acu1brwpstd2sadata1
      - sitscriptstorageaccnt

variables:
  ORG: PE
  APP: PST

  PREFIX: ACU1
  ENV: D2

  ADOProject: ADO_ADF
  PREFIXPRIMARY: ACU1
  APPPRIMARY: AOA

stages:
  - stage: Deploy_All_${{ variables.PREFIX }}_${{ variables.ORG }}_${{ variables.APP }}_RG_${{ variables.ENV }}
    jobs:
      - template: ..\..\..\.ado\ado-pipelines-STAGE.yml
        parameters:
          ORG:        ${{ variables.ORG }}
          APP:        ${{ variables.APP }}
          APPPRIMARY: ${{ variables.APPPRIMARY}}
          PREFIX:     ${{ variables.PREFIX }}
          ENV:        ${{ variables.ENV }}
          SP:         ${{ variables.ADOProject }}_${{ variables.PREFIX }}-${{ variables.ORG }}-${{ variables.APP }}-RG
          SPG0:       ${{ variables.ADOProject }}_${{ variables.PREFIXPRIMARY }}-${{ variables.ORG }}-${{ variables.APPPRIMARY }}-RG
          STAGE:      ${{ parameters.STAGE }}
          CN:         ${{ parameters.CN }}
          CN2:        ${{ parameters.CN2 }}
