name: Bug Report
description: Create a report to help us improve
# title: "[Bug]: "

labels: ["Needs: Triage 🔍","bug-report"]
# assignees:
#   - octocat

body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report!
        - Please ensure you reproduce this issue with the latest version of Bicep.
        - Please search for existing issues as a first preference to opening a new issue.
        - If this is not related to a bug or you need further information or investigation, consider opening a [Discussion](https://github.com/Azure/bicep/discussions)
        - If this is a Resource Provider or ARM API Specification issue, please open an issue in X.

  - type: textarea
    id: what-happened
    attributes:
      label: ~~ Description of the issue ~~
      description: A clear and concise description of what the bug is vs what you expected to happen
      placeholder: |
        You can provide Markdown examples/tagging here for PowerShell or CLI Etc.
        Bicep code snippets can be added below.
    validations:
      required: true

  - type: textarea
    id: version
    attributes:
      label: ~ The Bicep version ~
      description: What version of our software are you running?
      render: PowerShell
      placeholder: |
        # Bicep CLI
        bicep --version

        # AZ CLI
        az bicep version

        # VS code by navigating to the extensions tab and searching for Bicep
        # or executing below and providing version for "ms-azuretools.vscode-bicep"
        code --list-extensions --show-versions --category azure
    validations:
      required: true

  - type: textarea
    id: code-snippet
    attributes:
      label: ~ Sample Bicep code to reproduce the issue ~
      description: Please provide your Bicep code snippet below, this will automatically be formatted, no need for ```tagging```
      render: Bicep
      placeholder: |
        Provide sample Bicep code to reproduce the issue
        - Including default parameter values where possible.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Azure/bicep/blob/main/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true